### PR TITLE
fix: changed bg-100 card bg-white

### PR DESCRIPTION
**Pull request by kusman28**
Re: #13 #14
added divider hotline header fixed request
image

### CODE REVIEW

**Comment by jbienesdev** [comment]
@kusman28 page's bg-color is cutoff. You can create a new css file and import it inside `nuxt.config.js`, selecting `body` and change bg color.

Reference: https://nuxtjs.org/examples/global-css/

covid19zc-website 2020-03-30 01-06-41

Also change `perf` to `fix` 👍

**Comment by kusman28** [comment]
fixed
image

**Comment by jbienesdev** [comment]
@kusman28 Final changes, can you rename the css file to `main.css` and squash your commits into one then force push again.

**Comment by kusman28** [comment]
renamed css file
added header hotline and divider
image

**Pull request merged**
